# KSBs: K7, K8, S5, S18, K12, S12 (Automation), K16 (Data Security)
name: job-insights-app
region: lon # Change to your preferred region
services:
- name: web # Your main web application
  github:
    repo: billo-w/Pre-Project # Using your actual repo from the log
    deploy_on_push: true # Automatically deploy on push to main branch
    branch: main
  build_command: | # Build command for the web service (migrations removed)
    pip install --upgrade pip
    pip install -r requirements.txt
    echo "Web service build complete (migrations handled by job)."
  run_command: gunicorn wsgi:application
  envs:
  # Variables like FLASK_SECRET_KEY, DATABASE_URL, ADZUNA_*, AZURE_*
  # are now expected to be set as App-Level Environment Variables in the DO UI
  # and will be inherited by this service and the job.
  # Only define component-specific overrides or non-secret configurations here if necessary.
  - key: FLASK_CONFIG
    scope: RUN_AND_BUILD_TIME 
    value: "production"
  - key: FLASK_APP
    scope: RUN_AND_BUILD_TIME
    value: "wsgi.py"
  - key: SQLALCHEMY_ECHO
    scope: RUN_TIME
    value: "False"
  - key: FLASK_DEBUG
    scope: RUN_TIME
    value: "False"
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /
    initial_delay_seconds: 60 # Increased initial delay

# New section for Jobs
jobs:
- name: migrate # Name of your migration job
  kind: PRE_DEPLOY # Runs before new versions of services are deployed
  github:
    repo: billo-w/Pre-Project # Same repo and branch
    branch: main
  build_command: | # Build command for the job (installs dependencies)
    pip install --upgrade pip
    pip install -r requirements.txt
    echo "Migration job dependencies installed."
  run_command: flask db upgrade # The actual migration command
  envs:
    # These can also be inherited from App-Level if set there.
    # If they are only for the job, define them here.
    # For consistency, let's assume FLASK_APP and FLASK_CONFIG are also set at App-Level.
    # If you want job-specific values, define them here.
    # If these are defined at App-Level, this envs block for the job might become empty or be removed.
    - key: FLASK_APP
      scope: RUN_TIME # For a job, this means during its execution
      value: "wsgi.py"
    - key: FLASK_CONFIG
      scope: RUN_TIME
      value: "production"
    # DATABASE_URL for the job will be inherited from App-Level settings in the DO UI.

databases:
- cluster_name: db-postgresql-lon1-39455 # Your existing cluster
  db_name: defaultdb
  db_user: doadmin
  engine: PG
  name: db-postgresql-lon1-39455
  production: true
  version: "17"

ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
