# KSBs: K7, K8, S5, S18, K12, S12 (Automation), K16 (Data Security)
# This file defines the infrastructure for the Digital Ocean App Platform.
# It specifies the services, database, environment variables, and build/run commands,
# enabling automated, repeatable deployments from code.
name: job-insights-app
region: lon # Change to your preferred region, e.g., nyc3, ams3
services:
- name: web
  # App Platform builds from source, pulling from your GitHub repo.
  github:
    repo: billo-w/Pre-Project # IMPORTANT: Change this!
    branch: main
  build_command: |
    pip install --upgrade pip
    pip install -r requirements.txt
    flask db upgrade # Automatically run migrations on build
  # We simplify the run command to the most standard Gunicorn syntax.
  run_command: gunicorn wsgi:application
  # Environment variables with corrected, valid 'scope' values.
  envs:
  - key: FLASK_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    # This is needed at build time for `flask db upgrade` and run time for the app.
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: ADZUNA_APP_ID
    scope: RUN_TIME
    type: SECRET
  - key: ADZUNA_APP_KEY
    scope: RUN_TIME
    type: SECRET
  - key: AZURE_AI_ENDPOINT
    scope: RUN_TIME
    type: SECRET
  - key: AZURE_AI_KEY
    scope: RUN_TIME
    type: SECRET
  - key: FLASK_CONFIG # Ensures the app runs in production mode.
    scope: RUN_TIME
    value: "production"
  - key: FLASK_APP # This is needed for the 'flask db upgrade' command during build.
    scope: RUN_AND_BUILD_TIME
    value: "wsgi.py"
  - key: SQLALCHEMY_ECHO
    scope: RUN_TIME
    value: "False"
  - key: FLASK_DEBUG
    scope: RUN_TIME
    value: "False"
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs # Start with the smallest size and scale as needed
  # Defines health checks for operability (K11)
  health_check:
    http_path: / # App Platform will check the root URL to see if the app is alive.

# Defines the managed PostgreSQL database (K12, S7)
databases:
- name: db
  engine: PG # PostgreSQL
  version: "14" # Specify your PostgreSQL version
  # Production clusters are recommended, but 'db-s-1vcpu-1gb' is a good start.
  size: db-s-1vcpu-1gb
