name: job-insights-app
region: lon # Change to your preferred region, e.g., nyc3, ams3
services:
- name: web
  # App Platform builds from source, pulling from your GitHub repo.
  github:
    repo: billo-w/Pre-Project # IMPORTANT: Change this!
    branch: main
  build_command: |
    pip install --upgrade pip
    pip install -r requirements.txt
    flask db upgrade # Automatically run migrations on build
  run_command: gunicorn --worker-tmp-dir /dev/shm wsgi:application
  envs:
  - key: FLASK_SECRET_KEY
    scope: APP
    type: SECRET
  - key: DATABASE_URL
    scope: APP
    # This special syntax connects the app to the managed database defined below.
    value: ${db.DATABASE_URL}
  - key: ADZUNA_APP_ID
    scope: APP
    type: SECRET
  - key: ADZUNA_APP_KEY
    scope: APP
    type: SECRET
  - key: AZURE_AI_ENDPOINT
    scope: APP
    type: SECRET
  - key: AZURE_AI_KEY
    scope: APP
    type: SECRET
  - key: SQLALCHEMY_ECHO
    scope: APP
    value: "False"
  - key: FLASK_DEBUG
    scope: APP
    value: "False"
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs # Start with the smallest size and scale as needed
  # Defines health checks for operability (K11)
  health_check:
    http_path: / # App Platform will check the root URL to see if the app is alive.

# Defines the managed PostgreSQL database (K12, S7)
databases:
- name: db
  engine: PG # PostgreSQL
  version: "14" # Specify your PostgreSQL version
  # Production clusters are recommended, but 'db-s-1vcpu-1gb' is a good start.
  size: db-s-1vcpu-1gb